# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev
- ci

pool: dis-03

stages:
- stage: Build
  jobs:
  - job: build_pmwcas
    strategy:
      matrix:
        PMEM:
          backend: pmdk
          cmake_arg: PMDK 
        Volatile:
          backend: volatile
          cmake_arg: Volatile

    steps:
      - script: docker build -t pmwcas_$(Build.BuildId)_$(backend) --build-arg PMEM_BACKEND=$(cmake_arg) .
        displayName: 'Build Docker image'

- stage: Test
  jobs:
  - job: test
    strategy:
      matrix:
        PMEM:
          backend: pmdk
          cmake_arg: PMDK 
        Volatile:
          backend: volatile
          cmake_arg: Volatile
    steps:
      - script: docker run --name=pmwcas_$(Build.BuildId)_$(backend)_test pmwcas_$(Build.BuildId)_$(backend) 
        displayName: 'Run tests'

      - script: docker cp pmwcas_$(Build.BuildId)_$(backend)_test:/usr/src/pmwcas/build_tmp/Testing .
        displayName: 'Copy the test results'
      
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'CTest'
          testResultsFiles: '**/Testing/*/Test.xml'
  
  - job: clean
    dependsOn: test 
    steps:
      - script: docker rmi $(docker images --filter=reference="pmwcas_$(Build.BuildId)*" -q) --force
        displayName: 'Clean the containers'
        condition: always()
